version: '3'

services:
  postgres:
    container_name: order-service-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: order-service
      POSTGRES_DB: order-service
      POSTGRES_PASSWORD: order-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-app
    environment:
        POSTGRES_URL: jdbc:postgresql://postgres:5432/order-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - app-data:/app/data

volumes:
  postgres-data:
  app-data:
